;LABORATÓRIO 2 DE PROGRAMAÇÃO DO MICROCONTROLADOR 8051
;LEONARDO VINICIUS DE OLIVEIRA TOLEDO
;LINK PARA O LABORATORIO http://iris.sel.eesc.usp.br/sel614/lab3-A.pdf
;Lab 2.1

		ORG	0
		JB	P1.0, REL
		JNB	P1.0, REL0
JUMP:		SJMP	JUMP

REL:		
		MOV	A, #7FH
		MOV	DPTR, #1200H
		MOVX	@DPTR, A
		SJMP	JUMP

REL0:		
		MOV	A, #0FFH
		MOV	DPTR, #1200H
		MOVX	@DPTR, A
		SJMP	JUMP
		
		END